[versions]
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.1"
fabric-loader = "0.16.9"
fabric-api = "0.107.0+1.21.1"  # Fabric API versiyonu

meteor = "0.5.11-SNAPSHOT"  # Meteor snapshot – gerekirse meteorclient.com'dan güncel bak
loom = "1.8-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[bundles]
minecraft = ["minecraft", "yarn-mappings", "fabric-loader"]
