[versions]
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.1"
fabric-loader = "0.16.9"

meteor = "0.5.11-SNAPSHOT"  # En güncel snapshot için meteorclient.com'dan bak, genelde bu çalışır
meteor-repo = "https://meteorclient.com/maven"

loom = "1.8-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[libraries.bundles]
minecraft = ["minecraft", "yarn-mappings", "fabric-loader"]

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
